[pytest]
addopts = -ra -q --html=test_artifacts/pytest_report.html --self-contained-html --junitxml=test_artifacts/junit.xml --cov=mas_app --cov-report=term-missing --cov-report=html:test_artifacts/coverage_html
pythonpath = .
testpaths = tests
